version: '3.7'

services:
  db1:
    image: couchdb:latest

    volumes:
      - ./ser/db1/data:/opt/couchdb/data
      - ./ser/db1/config:/opt/couchdb/etc/local.d/

    ports:
      - 5984:5984

  db2:
    image: couchdb:latest

    volumes:
      - ./ser/db2/data:/opt/couchdb/data
      - ./ser/db2/config:/opt/couchdb/etc/local.d/

    ports:
      - 5985:5984